volumes:
  pgdata:

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    working_dir: /app
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: 
        - "8080:80"
    environment:
      DB_URL: "postgresql://db:5432/roller_derby_db"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: roller_derby_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
